### ISSUE TITLE
Gray line

### ISSUE THREAD

**Issue by christianhans** [sn-extensions/no-distraction-theme#5]
Might be a nit-picky detail but once enabled there is a thin gray line on the left hand side:

<img width="360" alt="screen shot 2019-02-15 at 1 34 10 pm" src="https://user-images.githubusercontent.com/355541/52877387-d8a9c100-3127-11e9-8651-fd00ac4481d2.png">

Once seen cannot be unseen. :-)

**Comment by christianhans** [comment]
I did find the CSS rule causing this:

<img width="973" alt="screen shot 2019-02-16 at 6 06 37 am" src="https://user-images.githubusercontent.com/355541/52898854-24547d00-31b1-11e9-9ecf-2d0481b883c8.png">

**Comment by christianhans** [comment]
See pull request #6

**Comment by mobitar** [comment]
Good catch, thanks!
