### ISSUE TITLE
Add title line to screen when No Distraction is activated

### ISSUE THREAD

**Issue by Raph33** [sn-extensions/no-distraction-theme#7]
I understand that No Distraction should have the least amount of clutter, but being about to see/edit the title of the note we're editing is pretty important. Perhaps we can have a one-button toggle to show/hide the title?

**Comment by mobitar** [comment]
Themes can't really create new interface elements. But you can always create a separate custom theme that addresses your use case directly.

**Comment by alandooz** [comment]
As it seems there is no solution on this, maybe this one could be closed.
